language: rust
rust: 
  - stable

arch:
  - amd64
  - arm64  # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below
  - ppc64le
  - s390x

script:
  - cargo build --verbose
  - cargo test --verbose
  - cd packed_struct_nostd_tests && cargo test --verbose
