name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
          matrix:
            include:
#              - arch: armv6
#                distro: jessie
#              - arch: armv7
 #               distro: ubuntu18.04
              - arch: aarch64
                distro: ubuntu18.04
              - arch: ppc64le
                distro: ubuntu18.04
#              - arch: s390x
#                distro: ubuntu18.04

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Build and Test
      id: build
      with:
            arch: ${{ matrix.arch }}
            distro: ${{ matrix.distro }}
            
            install: |
              apt-get update -q -y
              apt-get upgrade -q -y
              apt-get install build-essential curl -q -y
              curl https://sh.rustup.rs -sSf | bash -s -- -y

            run: |
              PATH="/root/.cargo/bin:${PATH}"
              cargo build --verbose
              cargo test --verbose
              cd packed_struct_nostd_tests && cargo test --verbose
